"use client";

// Developer/debug tool: replays a recorded motion session's stored skeleton
// frames so it's possible to actually WATCH the movement that produced a
// given care-metrics signal, instead of only seeing the final numbers.
// Reuses the exact same drawMotionSkeleton renderer as the live camera
// overlay, so what's shown here is a faithful playback, not a re-creation.

import { useEffect, useMemo, useRef, useState } from "react";
import {
  approximateHeadCenterFromShoulders,
  computeHandMotionVariability,
  computeMovementSmoothness,
  type Point3D,
} from "./motion-analysis";
import {
  MOTION_SAMPLE_RATE,
  getSessionFrames,
  parseSessionFrame,
  type ParsedMotionFrame,
} from "./pose-store";
import { drawMotionSkeleton } from "./skeleton-draw";
import type { DemoDetectionExplanation } from "./demo-personas";

const ROLLING_WINDOW = 10;
const CANVAS_WIDTH = 640;
const CANVAS_HEIGHT = 360;
const SPARKLINE_WIDTH = 640;
const SPARKLINE_HEIGHT = 40;

function wristPoint(frame: ParsedMotionFrame, hand: "left" | "right"): Point3D | null {
  const source = hand === "left" ? frame.leftHand : frame.rightHand;
  if (!source) return null;
  return { x: source[0], y: source[1], z: source[2] };
}

// Prefers whichever hand is actually detected in a frame, so a session
// doesn't read as "no motion" just because the person favored one hand.
function primaryHandPoint(frame: ParsedMotionFrame): Point3D | null {
  return wristPoint(frame, "left") ?? wristPoint(frame, "right");
}

function formatRelativeTime(ms: number) {
  const totalSeconds = Math.max(0, ms) / 1000;
  return `${totalSeconds.toFixed(1)}초`;
}

export type SessionReplaySource =
  // A real, actually-recorded session, loaded from IndexedDB by id.
  | { kind: "recorded"; sessionId: string }
  // A procedurally generated demo clip (app/demo-motion.ts) - not a real
  // recording. The raw frames are already generated by the caller.
  | { kind: "synthetic"; frames: number[][] };

export function SessionReplayPanel({
  source,
  sessionLabel,
  detectionExplanation,
  onClose,
}: {
  source: SessionReplaySource;
  sessionLabel?: string;
  /** Synthetic-only: the real, non-motion rule that actually counted this event. */
  detectionExplanation?: DemoDetectionExplanation;
  onClose: () => void;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const sparklineRef = useRef<HTMLCanvasElement>(null);
  // Synthetic frames are already in hand (no fetch needed), so they can seed
  // state immediately; recorded sessions start null and load in the effect
  // below. The parent renders this component with a `key` tied to the
  // source, so switching sources fully remounts it - no reset-on-change effect needed.
  const [frames, setFrames] = useState<ParsedMotionFrame[] | null>(() =>
    source.kind === "synthetic" ? source.frames.map(parseSessionFrame) : null,
  );
  const [loadFailed, setLoadFailed] = useState(false);
  const [frameIndex, setFrameIndex] = useState(0);
  const [playing, setPlaying] = useState(true);
  const [playbackRate, setPlaybackRate] = useState(1);

  useEffect(() => {
    if (source.kind !== "recorded") return;
    let cancelled = false;
    getSessionFrames(source.sessionId)
      .then((rawFrames) => {
        if (cancelled) return;
        setFrames(rawFrames.map(parseSessionFrame));
      })
      .catch(() => {
        if (!cancelled) setLoadFailed(true);
      });
    return () => {
      cancelled = true;
    };
  }, [source]);

  const primaryPoints = useMemo(
    () => (frames ? frames.map(primaryHandPoint) : []),
    [frames],
  );

  // Per-frame variability/smoothness over a trailing window - this is what
  // powers the sparkline and lets a developer jump straight to the moment
  // that produced a spike, instead of guessing from a single static snapshot.
  const variabilitySeries = useMemo(() => {
    return primaryPoints.map((_, index) => {
      const start = Math.max(0, index - ROLLING_WINDOW + 1);
      return computeHandMotionVariability(primaryPoints.slice(start, index + 1)) ?? 0;
    });
  }, [primaryPoints]);

  const smoothnessSeries = useMemo(() => {
    return primaryPoints.map((_, index) => {
      const start = Math.max(0, index - ROLLING_WINDOW + 1);
      return computeMovementSmoothness(primaryPoints.slice(start, index + 1)) ?? 0;
    });
  }, [primaryPoints]);

  // Playback loop, paced by the frames' own recorded relative_time_ms deltas
  // (not a fixed interval) so replay speed matches how the session was
  // actually sampled, scaled by playbackRate. Reads/writes frameIndex only
  // through the setState updater, so it never needs frameIndex itself in
  // its dependency list.
  useEffect(() => {
    if (!playing || !frames || frames.length < 2) return;
    let cancelled = false;
    let timeoutId: number;

    const scheduleNext = (delayMs: number) => {
      timeoutId = window.setTimeout(tick, Math.max(20, delayMs / playbackRate));
    };

    function tick() {
      if (cancelled) return;
      setFrameIndex((current) => {
        const next = current + 1;
        if (next >= frames!.length) {
          setPlaying(false);
          return current;
        }
        const rawDelta = frames![next].relativeTimeMs - frames![current].relativeTimeMs;
        const delta = rawDelta > 0 ? rawDelta : 1000 / MOTION_SAMPLE_RATE;
        scheduleNext(delta);
        return next;
      });
    }

    scheduleNext(1000 / MOTION_SAMPLE_RATE);
    return () => {
      cancelled = true;
      window.clearTimeout(timeoutId);
    };
  }, [playing, frames, playbackRate]);

  // Draw the current frame's skeleton.
  useEffect(() => {
    const canvas = canvasRef.current;
    const frame = frames?.[frameIndex];
    if (!canvas || !frame) return;
    const shoulderCenter = approximateHeadCenterFromShoulders(frame.body);
    const head =
      frame.head && shoulderCenter
        ? { ...frame.head, centerX: shoulderCenter.x, centerY: shoulderCenter.y }
        : null;
    drawMotionSkeleton(canvas, frame.body, frame.leftHand, frame.rightHand, head, frame.fullBodyVisible);
  }, [frames, frameIndex]);

  // Draw the variability sparkline plus a marker for the current frame.
  useEffect(() => {
    const canvas = sparklineRef.current;
    const context = canvas?.getContext("2d");
    if (!canvas || !context || variabilitySeries.length === 0) return;
    context.clearRect(0, 0, canvas.width, canvas.height);
    const max = Math.max(...variabilitySeries, 0.0001);
    const barWidth = canvas.width / variabilitySeries.length;
    variabilitySeries.forEach((value, index) => {
      const barHeight = Math.max(1, (value / max) * canvas.height);
      context.fillStyle = index === frameIndex ? "#2f6e4f" : "#c7ddc9";
      context.fillRect(index * barWidth, canvas.height - barHeight, Math.max(1, barWidth - 0.5), barHeight);
    });
  }, [variabilitySeries, frameIndex]);

  const currentFrame = frames?.[frameIndex] ?? null;
  const currentVariability = variabilitySeries[frameIndex];
  const currentSmoothness = smoothnessSeries[frameIndex];

  return (
    <div className="modal-backdrop" role="presentation" onMouseDown={onClose}>
      <section
        className="replay-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="replay-title"
        onMouseDown={(event) => event.stopPropagation()}
      >
        <button className="modal-close" type="button" onClick={onClose} aria-label="닫기">
          ×
        </button>
        <span className="section-kicker">
          {source.kind === "synthetic" ? "개발용 · 합성 시나리오 리플레이" : "개발용 세션 리플레이"}
        </span>
        <h2 id="replay-title">{sessionLabel ?? "기록된 좌표 세션"}</h2>
        {source.kind === "synthetic" ? (
          <p className="replay-note">
            <strong>실제 기록이 아니에요.</strong> 이 동작은 가상 페르소나 시나리오를 설명하기 위해
            절차적으로 생성한 예시 스켈레톤입니다. 이 이벤트가 감지됐을 때 사용자가 물리적으로 대략
            어떻게 움직였을지를 참고하는 개발용 화면이에요.
          </p>
        ) : (
          <p className="replay-note">
            이 화면은 개발 중 확인용입니다. 저장된 몸·손 좌표를 그대로 재생해서, 어떤 움직임이
            지표 변화를 만들었는지 직접 눈으로 확인할 수 있어요. 얼굴·영상·음성은 애초에
            저장되지 않아 여기서도 보이지 않습니다.
          </p>
        )}

        {source.kind === "synthetic" && detectionExplanation && (
          <div className="detection-basis">
            <span className="detection-basis-kicker">왜 이 신호로 잡혔을까요?</span>

            {detectionExplanation.detected.length > 0 ? (
              detectionExplanation.detected.map((detected, index) => (
                <p key={`${detected.type}-${index}`} className="detection-basis-evidence">
                  {detected.evidence}
                </p>
              ))
            ) : (
              <p className="detection-basis-evidence detection-basis-evidence-empty">
                이 동작 좌표를 분석해봤지만 반복 확인·지연·반응성 패턴이 감지되지 않았어요.
              </p>
            )}

            <p className="detection-basis-rule">{detectionExplanation.rule}</p>
            {detectionExplanation.metricLine && (
              <p className="detection-basis-metric">{detectionExplanation.metricLine}</p>
            )}
            {detectionExplanation.contributesToSignal && (
              <p className="detection-basis-flag">이번 주 케어 신호에 실제로 반영된 항목이에요.</p>
            )}
            <p className="detection-basis-caveat">
              위 감지 결과는 이 재생 화면의 좌표를 실제 앱과 똑같은 동작 분석 함수로 분석해서 나온
              진짜 결과예요(꾸며낸 설명이 아니에요). 실제 서비스에서는 이 동작 분석 결과와 마감 확인
              버튼 재실행·타이머 같은 기존 신호가 함께 집계돼요.
            </p>
          </div>
        )}

        {loadFailed && <p className="replay-empty">이 세션의 좌표 기록을 불러오지 못했어요.</p>}
        {!loadFailed && frames && frames.length === 0 && (
          <p className="replay-empty">이 세션에는 저장된 좌표 프레임이 없어요.</p>
        )}
        {!loadFailed && frames === null && <p className="replay-empty">좌표 기록을 불러오는 중...</p>}

        {frames && frames.length > 0 && currentFrame && (
          <>
            <div className="replay-canvas-wrap">
              <canvas ref={canvasRef} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} aria-label="리플레이 스켈레톤" />
              <div className="replay-flags">
                <span className={currentFrame.bodyDetected ? "on" : ""}>몸 인식</span>
                <span className={currentFrame.fullBodyVisible ? "on" : ""}>전신 프레임</span>
                <span className={currentFrame.leftHandDetected ? "on" : ""}>왼손</span>
                <span className={currentFrame.rightHandDetected ? "on" : ""}>오른손</span>
              </div>
            </div>

            <div className="replay-stats">
              <article>
                <span>구간 동작 변동성</span>
                <strong>{currentVariability !== undefined ? currentVariability.toFixed(2) : "–"}</strong>
              </article>
              <article>
                <span>구간 매끄러움(jerk)</span>
                <strong>{currentSmoothness !== undefined ? currentSmoothness.toFixed(4) : "–"}</strong>
              </article>
              <article>
                <span>프레임</span>
                <strong>
                  {frameIndex + 1} / {frames.length}
                </strong>
              </article>
              <article>
                <span>경과 시간</span>
                <strong>{formatRelativeTime(currentFrame.relativeTimeMs)}</strong>
              </article>
            </div>

            <canvas
              ref={sparklineRef}
              className="replay-sparkline"
              width={SPARKLINE_WIDTH}
              height={SPARKLINE_HEIGHT}
              aria-label="구간별 동작 변동성 그래프"
            />

            <input
              type="range"
              className="replay-scrubber"
              min={0}
              max={frames.length - 1}
              value={frameIndex}
              onChange={(event) => {
                setPlaying(false);
                setFrameIndex(Number(event.target.value));
              }}
              aria-label="재생 위치"
            />

            <div className="replay-controls">
              <button
                type="button"
                onClick={() => {
                  if (!playing && frameIndex >= frames.length - 1) setFrameIndex(0);
                  setPlaying((value) => !value);
                }}
              >
                {playing ? "일시정지" : frameIndex >= frames.length - 1 ? "처음부터 재생" : "재생"}
              </button>
              <div className="replay-speed" role="group" aria-label="재생 속도">
                {[0.5, 1, 2].map((rate) => (
                  <button
                    key={rate}
                    type="button"
                    className={playbackRate === rate ? "active" : ""}
                    onClick={() => {
                      if (frameIndex >= frames.length - 1) setFrameIndex(0);
                      setPlaybackRate(rate);
                    }}
                  >
                    {rate}x
                  </button>
                ))}
              </div>
            </div>
          </>
        )}
      </section>
    </div>
  );
}
